# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4264515a387ac667bceca9e860fcaa62c51b1f7d3c4b168c9ff92b9b4dce643119564ee62b120e3131a880d083c1f5b219a5a5d15d244d9572f7d7eb1e86fc47

test:
  secret_key_base: 47f065456e91399bf761113a9d7c3264ef6c2c92dc757b4023d6a399246e1019ea6f25ea19142961355ecdbffa9bc455e6ffad966898dbf7dff18fcbdb661b4a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
